# fly.toml app configuration file generated for gata-app on 2024-06-07T17:09:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gata-app'
primary_region = 'arn'
kill_timeout = 5
kill_signal = "SIGINT"
swap_size_mb = 512

[mounts]
source = "data"
destination = "/data"

[build]

[env]
  DEFAULT_CONTINGENT_SIZE= "600"
  AUTH0_CALLBACK= "https://gataersamla.no/callback"

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "10s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
